# Generated by Django 4.2.6 on 2023-11-15 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("euro_travel", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Euro_Travel",
            new_name="EuroTravel",
        ),
    ]
